// Package install wires autogit into an agent's configuration. Everything is
// computed first and written only on request, so `--dry-run` is the default and
// the tests never need to touch a real home directory.
package install

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"
)

// Marker identifies the hook entry and the command files autogit owns.
const Marker = "autogit hook"

const generatedNote = "<!-- generated by autogit; delete it and re-run `autogit install claude-code` to restore -->"

// Permissions autogit needs, or every commit asks the user for approval.
var toolPermissions = []string{"mcp__autogit__commit", "mcp__autogit__branch"}

// Options points the installer at a Claude Code configuration directory.
type Options struct {
	// Dir is the `.claude` directory. Tests pass a copy under t.TempDir().
	Dir string
	// Binary is what goes into the hook command.
	Binary string
	// Now stamps the backup file name.
	Now time.Time
}

// Write is one file the plan wants to create or replace.
type Write struct {
	Path string
	Data []byte
	Mode os.FileMode
	// Backup asks Apply to copy the existing file aside first.
	Backup bool
}

// Plan is what would change, before anything is written.
type Plan struct {
	Changes []string
	Writes  []Write
	Removes []string
	now     time.Time
}

// Empty reports whether there is nothing to do.
func (p *Plan) Empty() bool { return len(p.Writes) == 0 && len(p.Removes) == 0 }

const commandTemplate = `---
description: %s
argument-hint: %s
disable-model-invocation: true
---

%s

This command is handled by the deterministic ` + "`autogit hook`" + ` on
UserPromptSubmit, which blocks the prompt. If you are reading this text the hook
did not run: do nothing and say so.
`

type commandSpec struct {
	name        string
	description string
	argHint     string
}

var commands = []commandSpec{
	{"commit", "Deterministic git commit: stage, generate a message, validate, commit", "[all] [force]"},
	{"commit-msg", "Preview the commit message for the staged diff without committing", ""},
	{"branch", "Create a branch named <prefix>/<slug>", "[TICKET] [description]"},
}

// PlanInstall computes what `autogit install claude-code` would do.
func PlanInstall(opts Options) (*Plan, error) {
	opts = withDefaults(opts)
	p := &Plan{now: opts.Now}

	settingsPath := filepath.Join(opts.Dir, "settings.json")
	settings, existed, err := readSettings(settingsPath)
	if err != nil {
		return nil, err
	}

	before := mustMarshal(settings)
	addHook(settings, opts.Binary)
	addPermissions(settings)
	after := mustMarshal(settings)

	if !existed || !equalJSON(before, after) {
		p.Changes = append(p.Changes,
			fmt.Sprintf("settings.json: register the %s hook and allow %s",
				Marker, strings.Join(toolPermissions, ", ")))
		p.Writes = append(p.Writes, Write{
			Path: settingsPath, Data: after, Mode: 0o600, Backup: existed,
		})
	}

	for _, c := range commands {
		path := filepath.Join(opts.Dir, "commands", c.name+".md")
		data := []byte(fmt.Sprintf(commandTemplate, c.description, c.argHint, generatedNote))
		current, err := os.ReadFile(path) //nolint:gosec // a path the caller chose
		if err == nil && string(current) == string(data) {
			continue
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return nil, err
		}
		p.Changes = append(p.Changes, "commands/"+c.name+".md: write the slash-command stub")
		p.Writes = append(p.Writes, Write{Path: path, Data: data, Mode: 0o600, Backup: err == nil})
	}
	return p, nil
}

// PlanUninstall removes exactly what PlanInstall adds, and nothing else.
func PlanUninstall(opts Options) (*Plan, error) {
	opts = withDefaults(opts)
	p := &Plan{now: opts.Now}

	settingsPath := filepath.Join(opts.Dir, "settings.json")
	settings, existed, err := readSettings(settingsPath)
	if err != nil {
		return nil, err
	}
	if existed {
		before := mustMarshal(settings)
		removeHook(settings)
		removePermissions(settings)
		after := mustMarshal(settings)
		if !equalJSON(before, after) {
			p.Changes = append(p.Changes, "settings.json: remove the autogit hook and permissions")
			p.Writes = append(p.Writes, Write{Path: settingsPath, Data: after, Mode: 0o600, Backup: true})
		}
	}

	for _, c := range commands {
		path := filepath.Join(opts.Dir, "commands", c.name+".md")
		data, err := os.ReadFile(path) //nolint:gosec // a path the caller chose
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		// Never delete a file autogit did not write.
		if !strings.Contains(string(data), generatedNote) {
			p.Changes = append(p.Changes,
				"commands/"+c.name+".md: left alone, it was not written by autogit")
			continue
		}
		p.Changes = append(p.Changes, "commands/"+c.name+".md: remove")
		p.Removes = append(p.Removes, path)
	}
	return p, nil
}

// Apply writes the plan. Paths are resolved through symlinks first: on a setup
// where settings.json is a symlink into a dotfiles repo, a tmp+rename would
// replace the link with a real file and silently detach the config.
func (p *Plan) Apply() error {
	for _, w := range p.Writes {
		path, err := resolve(w.Path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			return err
		}
		if err := ensureWritable(path); err != nil {
			return err
		}
		if w.Backup {
			if err := backup(path, p.now); err != nil {
				return err
			}
		}
		if err := os.WriteFile(path, w.Data, w.Mode); err != nil {
			return err
		}
	}
	for _, path := range p.Removes {
		resolved, err := resolve(path)
		if err != nil {
			return err
		}
		if err := os.Remove(resolved); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	return nil
}

func withDefaults(opts Options) Options {
	if opts.Binary == "" {
		opts.Binary = "autogit"
	}
	if opts.Now.IsZero() {
		opts.Now = time.Now()
	}
	return opts
}

func resolve(path string) (string, error) {
	resolved, err := filepath.EvalSymlinks(path)
	if errors.Is(err, os.ErrNotExist) {
		return path, nil
	}
	if err != nil {
		return "", err
	}
	return resolved, nil
}

func ensureWritable(path string) error {
	f, err := os.OpenFile(path, os.O_WRONLY, 0) //nolint:gosec // a path the caller chose
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("%s is not writable: %w", path, err)
	}
	return f.Close()
}

// backup keeps every copy: a fixed `.bak` would be overwritten by the second
// install, losing the original.
func backup(path string, now time.Time) error {
	data, err := os.ReadFile(path) //nolint:gosec // the file we are about to replace
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	name := fmt.Sprintf("%s.autogit-%s.bak", path, now.UTC().Format("2006-01-02T15-04-05Z"))
	return os.WriteFile(name, data, 0o600) //nolint:gosec // sits next to the file it backs up
}

func readSettings(path string) (map[string]any, bool, error) {
	data, err := os.ReadFile(path) //nolint:gosec // a path the caller chose
	if errors.Is(err, os.ErrNotExist) {
		return map[string]any{}, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	settings := map[string]any{}
	if err := json.Unmarshal(data, &settings); err != nil {
		return nil, false, fmt.Errorf("%s: %w", path, err)
	}
	return settings, true, nil
}

// mustMarshal re-marshals the whole document. Go sorts map keys, so the first
// install reorders the file once and every install after that is a no-op.
func mustMarshal(settings map[string]any) []byte {
	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		// A map that came out of json.Unmarshal always marshals back.
		panic(err)
	}
	return append(data, '\n')
}

func equalJSON(a, b []byte) bool { return string(a) == string(b) }

func addHook(settings map[string]any, binary string) {
	removeHook(settings)

	hooks := childMap(settings, "hooks")
	groups, _ := hooks["UserPromptSubmit"].([]any)
	hooks["UserPromptSubmit"] = append(groups, map[string]any{
		"hooks": []any{map[string]any{
			"type":    "command",
			"command": binary + " hook",
			// Claude Code's own ceiling; autogit stops itself at 110s.
			"timeout": float64(120),
		}},
	})
}

func removeHook(settings map[string]any) {
	hooks, ok := settings["hooks"].(map[string]any)
	if !ok {
		return
	}
	groups, ok := hooks["UserPromptSubmit"].([]any)
	if !ok {
		return
	}

	kept := make([]any, 0, len(groups))
	for _, raw := range groups {
		group, ok := raw.(map[string]any)
		if !ok {
			kept = append(kept, raw)
			continue
		}
		entries, ok := group["hooks"].([]any)
		if !ok {
			kept = append(kept, raw)
			continue
		}
		keptEntries := make([]any, 0, len(entries))
		for _, entry := range entries {
			if e, ok := entry.(map[string]any); ok {
				if cmd, _ := e["command"].(string); strings.Contains(cmd, Marker) {
					continue
				}
			}
			keptEntries = append(keptEntries, entry)
		}
		if len(keptEntries) == 0 {
			continue
		}
		group["hooks"] = keptEntries
		kept = append(kept, group)
	}

	if len(kept) == 0 {
		delete(hooks, "UserPromptSubmit")
	} else {
		hooks["UserPromptSubmit"] = kept
	}
	if len(hooks) == 0 {
		delete(settings, "hooks")
	}
}

func addPermissions(settings map[string]any) {
	permissions := childMap(settings, "permissions")
	allow, _ := permissions["allow"].([]any)
	for _, want := range toolPermissions {
		if !containsAny(allow, want) {
			allow = append(allow, want)
		}
	}
	permissions["allow"] = allow
}

func removePermissions(settings map[string]any) {
	permissions, ok := settings["permissions"].(map[string]any)
	if !ok {
		return
	}
	allow, ok := permissions["allow"].([]any)
	if !ok {
		return
	}
	kept := make([]any, 0, len(allow))
	for _, entry := range allow {
		if s, ok := entry.(string); ok && slices.Contains(toolPermissions, s) {
			continue
		}
		kept = append(kept, entry)
	}
	if len(kept) == 0 {
		delete(permissions, "allow")
	} else {
		permissions["allow"] = kept
	}
	if len(permissions) == 0 {
		delete(settings, "permissions")
	}
}

func childMap(parent map[string]any, key string) map[string]any {
	child, ok := parent[key].(map[string]any)
	if !ok {
		child = map[string]any{}
		parent[key] = child
	}
	return child
}

func containsAny(list []any, want string) bool {
	for _, entry := range list {
		if s, ok := entry.(string); ok && s == want {
			return true
		}
	}
	return false
}
